# Generated by Django 2.1.7 on 2019-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogProject', '0002_auto_20190520_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
