# Generated by Django 2.1.7 on 2019-05-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogProject', '0003_auto_20190520_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_like',
        ),
    ]
